# Generated by Django 5.0 on 2024-01-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.CharField(max_length=10)),
                ('computer_choice', models.CharField(max_length=10)),
                ('winner', models.CharField(max_length=10)),
            ],
        ),
    ]
