# Generated by Django 5.0 on 2024-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headtails',
            name='user_choice',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
